const SUPPORTED_SHELLS = ["zsh", "bash"] as const;

const HELP = `usage: maw shellenv <shell>

Emit shell init code for eval-style installation.

  Install (zsh):
    eval "$(maw shellenv zsh)"     # add to ~/.zshrc

  Install (bash):
    eval "$(maw shellenv bash)"    # add to ~/.bashrc

Available shells: ${SUPPORTED_SHELLS.join(", ")}
(fish deferred to v2 — see #812)

The emitted snippet installs a maw() function that adds:
  maw warp [<oracle>]    cd into an oracle's repo (default: mawjs)
  maw <other>            pass-through to the real binary

`;
function bashSnippet(): string { return `# maw shellenv (bash) — generated by 'maw shellenv bash'
# Install: eval "$(maw shellenv bash)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# TODO(shellenv): tab completion for 'maw warp' via complete -F + 'command maw completions oracles'
`; }
function zshSnippet(): string { return `# maw shellenv (zsh) — generated by 'maw shellenv zsh'
# Install: eval "$(maw shellenv zsh)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# claude() wrapper —
#   • adds --dangerously-skip-permissions (default-on; redefine claude() to opt out)
#   • adds --channels from $MAW_CLAUDE_CHANNELS (default: discord plugin;
#     set MAW_CLAUDE_CHANNELS="" to disable, unset = use default)
#   • auto-fallback when --continue fails (no prior session)
# Lets \`maw wake\` send a clean \`claude --continue\` instead of a verbose
# \`{ X || Y; }\` fallback chain. (#1896)
claude() {
  local channels="\${MAW_CLAUDE_CHANNELS-plugin:discord@claude-plugins-official}"
  local opts=(--dangerously-skip-permissions)
  [[ -n "$channels" ]] && opts+=(--channels "$channels")
  if [[ "$*" == *"--continue"* ]]; then
    command claude "\${opts[@]}" "$@" || command claude "\${opts[@]}" "\${@/--continue/}"
  else
    command claude "\${opts[@]}" "$@"
  fi
}
# claude46 — Opus 4.6 (1M context). Delegates to claude() for --continue fallback.
claude46() {
  ANTHROPIC_MODEL="claude-opus-4-6[1m]" claude "$@"
}
# claude47 — Opus 4.7. Delegates to claude() for --continue fallback.
claude47() {
  ANTHROPIC_MODEL="claude-opus-4-7" claude "$@"
}
# thclaws — CLI REPL mode. --accept-all = auto-approve (like --dangerously-skip-permissions).
thclaws-cli() {
  thclaws --cli --accept-all "$@"
}
# TODO(shellenv): tab completion for 'maw warp' via compdef + 'command maw completions oracles'
`; }
function parseFlags(args: string[]) {
  const out: Record<string, unknown> & { _: string[] } = { _: [] };
  for (const tok of args) {
    const canonical = tok === "-h" ? "--help" : tok;
    if (canonical === "--help") out[canonical] = true;
    else if (tok.startsWith("-")) out[canonical] = true;
    else out._.push(tok);
  }
  return out;
}
export default async function handle(ctx: { source: string; args: string[] }) {
  const args = ctx.source === "cli" ? ctx.args : [];
  const flags = parseFlags(args);
  const shell = flags._[0];
  if (flags["--help"]) return { ok: true, output: HELP };
  if (!shell) {
    const msg = `Error: shell '' not supported. Available: ${SUPPORTED_SHELLS.join(", ")}`;
    return { ok: false, error: msg, output: msg };
  }
  if (shell === "zsh") return { ok: true, output: zshSnippet() };
  if (shell === "bash") return { ok: true, output: bashSnippet() };
  const msg = `Error: shell '${shell}' not supported. Available: ${SUPPORTED_SHELLS.join(", ")}`;
  return { ok: false, error: msg, output: msg };
}
