import { Host } from "@extism/as-pdk";
import { hostExec } from "../../../../packages/wasm-sdk/assembly";
export function myAbort(message: string | null, fileName: string | null, lineNumber: u32, columnNumber: u32): void {}
class ParsedString { value: string; next: i32; constructor(value: string, next: i32) { this.value = value; this.next = next; } }
class Tool { name: string; flag: string; required: bool; notes: string; constructor(name: string, flag: string, required: bool, notes: string = "") { this.name = name; this.flag = flag; this.required = required; this.notes = notes; } }
const TOOLS = [new Tool("bun", "--version", true), new Tool("gh", "--version", true), new Tool("ghq", "--version", true), new Tool("git", "--version", true), new Tool("tmux", "-V", true), new Tool("uv", "--version", false), new Tool("uvx", "--version", false, "provided by uv")];
export function handle(): i32 { const args = extractArgs(Host.inputString()); const sub = args.length > 0 ? args[0] : "tools"; if (sub != "tools") return finish(true, "unknown subcommand: " + sub + "\nusage: maw check [tools]", null); let out = "\nmaw check tools\n\nRequired:"; let reqOk = 0; let optOk = 0; let missing = new Array<string>(); for (let i = 0; i < TOOLS.length; i++) { const t = TOOLS[i]; const r = check(t); const row = "\n  " + (r.present ? "\u001b[32m✓\u001b[0m " : "\u001b[31m✗\u001b[0m ") + pad(t.name, 8) + (r.present ? (r.version == "" ? "" : "  " + r.version) + (t.notes == "" ? "" : "  \u001b[90m(" + t.notes + ")\u001b[0m") : "  \u001b[90mnot installed\u001b[0m"); if (t.required) { out += row; if (r.present) reqOk++; } else { if (i == 5) out += "\n\nOptional (Python plugins):"; out += row; if (r.present) optOk++; } if (!r.present) missing.push(t.name); } if (missing.length > 0) { out += "\n\nMissing:"; for (let i = 0; i < missing.length; i++) out += "\n  \u001b[31m✗\u001b[0m " + pad(missing[i], 16); } out += "\n\n" + reqOk.toString() + " required ✓  ·  " + optOk.toString() + " optional ✓  ·  " + (missing.length > 0 ? "\u001b[31m" + missing.length.toString() + " missing\u001b[0m" : "0 missing") + "\n"; return finish(true, out, null); }
class CheckResult { present: bool; version: string; constructor(present: bool, version: string) { this.present = present; this.version = version; } }
function check(t: Tool): CheckResult { const response = hostExec("{\"cmd\":" + quote(t.name) + ",\"args\":[" + quote(t.flag) + "],\"allowNonZero\":true,\"timeoutMs\":2000}"); if (response.indexOf("\"ok\":true") < 0) return new CheckResult(false, ""); const stdout = jsonStringField(response, "stdout"); const stderr = jsonStringField(response, "stderr"); return new CheckResult(true, firstVersion(stdout + stderr)); }
function firstVersion(s: string): string { let start = -1; for (let i = 0; i < s.length; i++) if (isDigit(s.charCodeAt(i))) { start = i; break; } if (start < 0) return ""; let end = start; while (end < s.length) { const c = s.charCodeAt(end); if (!(isDigit(c) || c == 46)) break; end++; } return s.slice(start, end); }
function isDigit(c: i32): bool { return c >= 48 && c <= 57; }
function pad(value: string, width: i32): string { return value.length >= width ? value : value + " ".repeat(width - value.length); }
function extractArgs(json: string): string[] { const marker = "\"args\":["; const start = json.indexOf(marker); if (start < 0) return []; let i = start + marker.length; const out = new Array<string>(); while (i < json.length && json.charAt(i) != "]") { if (json.charAt(i) == "\"") { const parsed = readJsonString(json, i); out.push(parsed.value); i = parsed.next; } else i++; } return out; }
function jsonStringField(json: string, key: string): string { const marker = "\"" + key + "\":"; const i = json.indexOf(marker); if (i < 0) return ""; let j = i + marker.length; while (j < json.length && json.charAt(j) != "\"") j++; if (j >= json.length) return ""; return readJsonString(json, j).value; }
function readJsonString(s: string, start: i32): ParsedString { let out = ""; let i = start + 1; while (i < s.length) { const ch = s.charAt(i); if (ch == "\\") { i++; if (i >= s.length) break; const e = s.charAt(i); if (e == "n") out += "\n"; else if (e == "r") out += "\r"; else if (e == "t") out += "\t"; else out += e; } else if (ch == "\"") return new ParsedString(out, i + 1); else out += ch; i++; } return new ParsedString(out, i); }
function finish(ok: bool, output: string | null, error: string | null): i32 { Host.outputString(resultJson(ok, output, error)); return 0; }
function resultJson(ok: bool, output: string | null, error: string | null): string { let json = ok ? "{\"ok\":true" : "{\"ok\":false"; if (ok) json += ",\"output\":" + (output === null ? "null" : quote(output)); else if (error !== null) json += ",\"error\":" + quote(error); return json + "}"; }
function quote(value: string): string { let out = "\""; for (let i = 0; i < value.length; i++) { const code = value.charCodeAt(i); const ch = value.charAt(i); if (ch == "\\") out += "\\\\"; else if (ch == "\"") out += "\\\""; else if (ch == "\n") out += "\\n"; else if (ch == "\r") out += "\\r"; else if (ch == "\t") out += "\\t"; else if (code < 32 || code > 126) out += "\\u" + hex4(code); else out += ch; } return out + "\""; }
function hex4(code: i32): string { const digits = "0123456789abcdef"; return digits.charAt((code >> 12) & 15) + digits.charAt((code >> 8) & 15) + digits.charAt((code >> 4) & 15) + digits.charAt(code & 15); }
