import { Host } from "@extism/as-pdk";

export function myAbort(message: string | null, fileName: string | null, lineNumber: u32, columnNumber: u32): void {}

const HELP = "usage: maw shellenv <shell>\n\n" +
  "Emit shell init code for eval-style installation.\n\n" +
  "  Install (zsh):\n" +
  "    eval \"$(maw shellenv zsh)\"     # add to ~/.zshrc\n\n" +
  "  Install (bash):\n" +
  "    eval \"$(maw shellenv bash)\"    # add to ~/.bashrc\n\n" +
  "Available shells: zsh, bash\n" +
  "(fish deferred to v2 — see #812)\n\n" +
  "The emitted snippet installs a maw() function that adds:\n" +
  "  maw warp [<oracle>]    cd into an oracle's repo (default: mawjs)\n" +
  "  maw <other>            pass-through to the real binary\n\n";

const BASH_SNIPPET = `# maw shellenv (bash) — generated by 'maw shellenv bash'
# Install: eval "$(maw shellenv bash)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# TODO(shellenv): tab completion for 'maw warp' via complete -F + 'command maw completions oracles'
`;

const ZSH_SNIPPET = `# maw shellenv (zsh) — generated by 'maw shellenv zsh'
# Install: eval "$(maw shellenv zsh)"
maw() {
  if [[ "$1" == "warp" ]]; then
    shift
    local target="\${1:-mawjs}"
    if [[ "$target" == *:* ]]; then
      echo "maw warp: qualified <oracle>:<node> not supported yet (see #804)" >&2
      return 1
    fi
    local path
    if ! path="$(command maw locate "$target" --path 2>/dev/null)" || [[ -z "$path" ]]; then
      echo "maw warp: oracle '$target' not found" >&2
      return 1
    fi
    builtin cd "$path"
  else
    command maw "$@"
  fi
}
# claude() wrapper —
#   • adds --dangerously-skip-permissions (default-on; redefine claude() to opt out)
#   • adds --channels from $MAW_CLAUDE_CHANNELS (default: discord plugin;
#     set MAW_CLAUDE_CHANNELS="" to disable, unset = use default)
#   • auto-fallback when --continue fails (no prior session)
# Lets \`maw wake\` send a clean \`claude --continue\` instead of a verbose
# \`{ X || Y; }\` fallback chain. (#1896)
claude() {
  local channels="\${MAW_CLAUDE_CHANNELS-plugin:discord@claude-plugins-official}"
  local opts=(--dangerously-skip-permissions)
  [[ -n "$channels" ]] && opts+=(--channels "$channels")
  if [[ "$*" == *"--continue"* ]]; then
    command claude "\${opts[@]}" "$@" || command claude "\${opts[@]}" "\${@/--continue/}"
  else
    command claude "\${opts[@]}" "$@"
  fi
}
# claude46 — Opus 4.6 (1M context). Delegates to claude() for --continue fallback.
claude46() {
  ANTHROPIC_MODEL="claude-opus-4-6[1m]" claude "$@"
}
# claude47 — Opus 4.7. Delegates to claude() for --continue fallback.
claude47() {
  ANTHROPIC_MODEL="claude-opus-4-7" claude "$@"
}
# thclaws — CLI REPL mode. --accept-all = auto-approve (like --dangerously-skip-permissions).
thclaws-cli() {
  thclaws --cli --accept-all "$@"
}
# TODO(shellenv): tab completion for 'maw warp' via compdef + 'command maw completions oracles'
`;

export function handle(): i32 {
  const input = Host.inputString();
  const args = extractArgs(input);
  let ok = true;
  let output: string | null = null;
  let error: string | null = null;
  const help = contains(args, "--help") || contains(args, "-h");
  const shell = firstPositional(args);
  if (help) {
    output = HELP;
  } else if (shell == "") {
    ok = false;
    error = "missing shell argument";
  } else if (shell == "zsh") {
    output = ZSH_SNIPPET;
  } else if (shell == "bash") {
    output = BASH_SNIPPET;
  } else {
    ok = false;
    error = "unsupported shell: " + shell;
  }
  Host.outputString(resultJson(ok, output, error));
  return 0;
}

function firstPositional(args: string[]): string {
  for (let i = 0; i < args.length; i++) if (!args[i].startsWith("-")) return args[i];
  return "";
}
function contains(args: string[], needle: string): bool { for (let i = 0; i < args.length; i++) if (args[i] == needle) return true; return false; }
function extractArgs(json: string): string[] {
  const marker = "\"args\":[";
  const start = json.indexOf(marker);
  if (start < 0) return [];
  let i = start + marker.length;
  const out = new Array<string>();
  while (i < json.length && json.charAt(i) != "]") {
    if (json.charAt(i) == "\"") {
      const parsed = readJsonString(json, i);
      out.push(parsed.value);
      i = parsed.next;
    } else i++;
  }
  return out;
}
class ParsedString { value: string; next: i32; constructor(value: string, next: i32) { this.value = value; this.next = next; } }
function readJsonString(s: string, start: i32): ParsedString {
  let out = "";
  let i = start + 1;
  while (i < s.length) {
    const ch = s.charAt(i);
    if (ch == "\\") { i++; if (i >= s.length) break; const e = s.charAt(i); if (e == "n") out += "\n"; else if (e == "r") out += "\r"; else if (e == "t") out += "\t"; else out += e; }
    else if (ch == "\"") return new ParsedString(out, i + 1);
    else out += ch;
    i++;
  }
  return new ParsedString(out, i);
}
function resultJson(ok: bool, output: string | null, error: string | null): string {
  let json = ok ? "{\"ok\":true" : "{\"ok\":false";
  if (output !== null) json += ",\"output\":" + quote(output);
  if (error !== null) json += ",\"error\":" + quote(error);
  return json + "}";
}
function quote(value: string): string {
  let out = "\"";
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    const ch = value.charAt(i);
    if (ch == "\\") out += "\\\\";
    else if (ch == "\"") out += "\\\"";
    else if (ch == "\n") out += "\\n";
    else if (ch == "\r") out += "\\r";
    else if (ch == "\t") out += "\\t";
    else if (code < 32 || code > 126) out += "\\u" + hex4(code);
    else out += ch;
  }
  return out + "\"";
}
function hex4(code: i32): string {
  const digits = "0123456789abcdef";
  return digits.charAt((code >> 12) & 15) + digits.charAt((code >> 8) & 15) + digits.charAt((code >> 4) & 15) + digits.charAt(code & 15);
}
