import { Host } from "@extism/as-pdk";
import { capture, fsList, fsRead, fsWrite, hostExec, listSessions } from "../../../../packages/wasm-sdk/assembly";
export function myAbort(message: string | null, fileName: string | null, lineNumber: u32, columnNumber: u32): void {}
class ParsedString { value: string; next: i32; constructor(value: string, next: i32) { this.value = value; this.next = next; } }
export function handle(): i32 { const args = extractArgs(Host.inputString()); if (args.length > 0 && (args[0] == "ls" || args[0] == "list")) return parkLs(); const target = args.length > 0 ? args[0] : "codex-1"; const note = args.length > 1 ? args.slice(1).join(" ") : ""; listSessions("{}"); const pane = capture("{\"target\":" + quote(target) + ",\"format\":\"cwd\"}"); if (pane.indexOf("\"ok\":true") < 0) return finish(false, null, "window not found: " + target); const cwd = jsonStringField(pane, "content"); const branch = git(cwd, ["branch", "--show-current"]); const lastCommit = git(cwd, ["log", "-1", "--oneline"]); const dirty = git(cwd, ["status", "--short"]); const dirtyJson = stringLinesJson(dirty); const state = "{\n  \"window\": " + quote(target) + ",\n  \"session\": \"wasm-parity\",\n  \"branch\": " + quote(branch) + ",\n  \"cwd\": " + quote(cwd) + ",\n  \"lastCommit\": " + quote(lastCommit) + ",\n  \"dirtyFiles\": " + dirtyJson + ",\n  \"note\": " + quote(note) + ",\n  \"parkedAt\": \"2026-06-24T00:00:00.000Z\"\n}\n"; const wr = fsWrite("{\"path\":\"/state/parked/" + target + ".json\",\"content\":" + quote(state) + ",\"mode\":\"overwrite\"}"); if (wr.indexOf("\"ok\":true") < 0) return finish(false, null, hostError(wr, "maw.fs.write failed")); return finish(true, "\u001b[32m✓\u001b[0m parked \u001b[33m" + target + "\u001b[0m" + (note == "" ? "" : " — \"" + note + "\""), null); }
function parkLs(): i32 { const list = fsList("{\"path\":\"/state/parked\",\"recursive\":false,\"includeDirs\":false}"); const files = jsonArrayStrings(list, "entries"); if (files.length == 0) return finish(true, "\u001b[90mno parked tabs\u001b[0m", null); let out = "\n\u001b[36mPARKED\u001b[0m (" + files.length.toString() + "):\n"; for (let i = 0; i < files.length; i++) { const body = readContent("/state/parked/" + files[i]); const dirty = jsonArrayStrings(body, "dirtyFiles").length; out += "\n  \u001b[33m" + jsonStringField(body, "window") + "\u001b[0m  \"" + jsonStringField(body, "note") + "\"  0m ago  " + jsonStringField(body, "branch") + "  " + (dirty > 0 ? "\u001b[33m" + dirty.toString() + " dirty\u001b[0m" : "\u001b[32mclean\u001b[0m"); } out += "\n"; return finish(true, out, null); }
function git(cwd: string, args: string[]): string { let req = "{\"cmd\":\"git\",\"args\":[\"-C\"," + quote(cwd); for (let i = 0; i < args.length; i++) req += "," + quote(args[i]); req += "],\"allowNonZero\":true,\"timeoutMs\":2000}"; const out = hostExec(req); if (out.indexOf("\"ok\":true") < 0) return ""; return trim(jsonStringField(out, "stdout")); }
function readContent(path: string): string { const out = fsRead("{\"path\":" + quote(path) + ",\"encoding\":\"utf8\"}"); return out.indexOf("\"ok\":true") < 0 ? "" : jsonStringField(out, "content"); }
function stringLinesJson(s: string): string { if (trim(s) == "") return "[]"; const lines = trim(s).split("\n"); let out = "["; for (let i = 0; i < lines.length; i++) { if (i > 0) out += ","; out += quote(trim(lines[i])); } return out + "]"; }
function hostError(response: string, fallback: string): string { const error = jsonStringField(response, "error"); return error == "" ? fallback : error; }
function extractArgs(json: string): string[] { const marker = "\"args\":["; const start = json.indexOf(marker); if (start < 0) return []; let i = start + marker.length; const out = new Array<string>(); while (i < json.length && json.charAt(i) != "]") { if (json.charAt(i) == "\"") { const parsed = readJsonString(json, i); out.push(parsed.value); i = parsed.next; } else i++; } return out; }
function jsonArrayStrings(json: string, key: string): string[] { const out = new Array<string>(); const marker = "\"" + key + "\":"; const i = json.indexOf(marker); if (i < 0) return out; let j = i + marker.length; while (j < json.length && json.charAt(j) != "[") j++; if (j >= json.length) return out; j++; while (j < json.length && json.charAt(j) != "]") { if (json.charAt(j) == "\"") { const parsed = readJsonString(json, j); out.push(parsed.value); j = parsed.next; } else j++; } return out; }
function jsonStringField(json: string, key: string): string { const marker = "\"" + key + "\":"; const i = json.indexOf(marker); if (i < 0) return ""; let j = i + marker.length; while (j < json.length && json.charAt(j) != "\"") j++; if (j >= json.length) return ""; return readJsonString(json, j).value; }
function readJsonString(s: string, start: i32): ParsedString { let out = ""; let i = start + 1; while (i < s.length) { const ch = s.charAt(i); if (ch == "\\") { i++; if (i >= s.length) break; const e = s.charAt(i); if (e == "n") out += "\n"; else if (e == "r") out += "\r"; else if (e == "t") out += "\t"; else out += e; } else if (ch == "\"") return new ParsedString(out, i + 1); else out += ch; i++; } return new ParsedString(out, i); }
function trim(value: string): string { let start = 0; let end = value.length; while (start < end && isSpace(value.charCodeAt(start))) start++; while (end > start && isSpace(value.charCodeAt(end - 1))) end--; return value.slice(start, end); }
function isSpace(c: i32): bool { return c == 32 || c == 9 || c == 10 || c == 13; }
function finish(ok: bool, output: string | null, error: string | null): i32 { Host.outputString(resultJson(ok, output, error)); return 0; }
function resultJson(ok: bool, output: string | null, error: string | null): string { let json = ok ? "{\"ok\":true" : "{\"ok\":false"; if (ok) json += ",\"output\":" + (output === null ? "null" : quote(output)); else if (error !== null) json += ",\"error\":" + quote(error); return json + "}"; }
function quote(value: string): string { let out = "\""; for (let i = 0; i < value.length; i++) { const code = value.charCodeAt(i); const ch = value.charAt(i); if (ch == "\\") out += "\\\\"; else if (ch == "\"") out += "\\\""; else if (ch == "\n") out += "\\n"; else if (ch == "\r") out += "\\r"; else if (ch == "\t") out += "\\t"; else if (code < 32 || code > 126) out += "\\u" + hex4(code); else out += ch; } return out + "\""; }
function hex4(code: i32): string { const digits = "0123456789abcdef"; return digits.charAt((code >> 12) & 15) + digits.charAt((code >> 8) & 15) + digits.charAt((code >> 4) & 15) + digits.charAt(code & 15); }
